### PR TITLE
Ruby 2.4.0 Fixnum to Integer repairs

### PR DESCRIPTION
**Pull request by MacCracken**
repairing Fixnum depreciation with ruby 2.4.0

### CODE REVIEW

**Comment by jordiponsllaurado** [comment]
Do we know when this is going to be merged?

**Comment by profsmallpine** [comment]
@MacCracken Does this need any more review? It seems pretty straightforward and would be nice to get this deprecation fixed for us folks on Rails 5. I would help but I'm not sure there is anything to do here.

**Comment by MacCracken** [comment]
I believe all the fixes are in there. its on @cheezy to review and update.

**Comment by profsmallpine** [comment]
ping @cheezy

**Comment by cheezy** [comment]
On this now.  Will merge and make a new release this evening.

**Pull request merged**
